# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Eventbrite_dev

# test:
#   <<: *default
#   database: Eventbrite_test

production:
  <<: *default
  database: soniapavageau_thp_database
  username: Eventbrite
  password: Rails.application.credentials.database[:password]
  timeout: 5000
  host: postgresql-soniapavageau.alwaysdata.net
